### PR TITLE
wine-tkg-git: fix user revert patches applying

### PR DESCRIPTION
**Pull request by idprophecy**
Just a small mistake made it not working.

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
Good point. I should sleep more.

**Comment by idprophecy** [comment]
Also, shoudn't be there -R since it's been supposed to revert the patch?

**Comment by Tk-Glitch** [comment]
Oh yes, definitely. Fixed : https://github.com/Tk-Glitch/PKGBUILDS/commit/37cbc11e35128bf87c72d92966dd78c95f1d4ce7

**Comment by idprophecy** [comment]
One last thing, ${F} in the condition should be ${_f}.

**Comment by Tk-Glitch** [comment]
FFS :D

**Pull request merged**
