### PR TITLE
linux56-rc-tkg: Fix for diffconfig not applying

### PR DESCRIPTION
**Pull request by Faalagorn**
I think it happened for 55-rc as well?

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
Oh yeah, all rc's for sure 🐸 
Thanks

**Comment by Faalagorn** [comment]
Thanks for pulling that in, although while the kernel now compiles for me, I got a broken fragment, so I think there's still something frogged :P

Here's the resulting fragment file content:

```I/O error[2]: No such file or directory

Usage: diffconfig [-h] [-m] [<config1> <config2>]

Diffconfig is a simple utility for comparing two .config files.
Using standard diff to compare .config files often includes extraneous and
distracting information.  This utility produces sorted output with only the
changes in configuration values between the two files.

Added and removed items are shown with a leading plus or minus, respectively.
Changed items show the old and new values on a single line.

If -m is specified, then output will be in "merge" style, which has the
changed and new values in kernel config option format.

If no config files are specified, .config and .config.old are used.

Example usage:
 $ diffconfig .config config-with-some-changes
-EXT2_FS_XATTR  n
 CRAMFS  n -> y
 EXT2_FS  y -> n
 LOG_BUF_SHIFT  14 -> 16
 PRINTK_TIME  n -> y
```

**Comment by openglfreak** [comment]
Will investigate tomorrow.

**Comment by openglfreak** [comment]
There's a doubled `}` in the line.
I'm making a PR that makes the changing of path for -rc kernels unnecessary, so this can't happen again.

**Pull request merged**
