### PR TITLE
[mesa-tkg-git] Correction of inaccuracies in the description.

### PR DESCRIPTION
**Pull request by Kerrung**
Without this, it will work poorly.

### CODE REVIEW

**Comment by Kerrung** [comment]
@Tk-Glitch , should I add as many frogs as possible for my PR to accept? Thanks you.

**Comment by Tk-Glitch** [comment]
Is that a real question? What's up with the line breaks? What's the point of that PR to begin with? It serves no purpose, so for everyone's sanity I'll close. Sorry bud.

**Comment by Kerrung** [comment]
M

> Is that a real question? What's up with the line breaks? What's the point of that PR to begin with? It serves no purpose, so for everyone's sanity I'll close. Sorry bud.

Mesa is an open-source implementation of the OpenGL and Vulkan specifications, not only OpenGL.

**Comment by Kerrung** [comment]
> Is that a real question? What's up with the line breaks? What's the point of that PR to begin with? It serves no purpose, so for everyone's sanity I'll close. Sorry bud.

@Tk-Glitch , Mesa is an open-source implementation of the OpenGL and Vulkan specifications, not only OpenGL. But in your mesa-git description ""an open-source implementation of the OpenGL specification".

**Comment by Tk-Glitch** [comment]
Yes I have read your PR. But then what about OpenGL ES, EGL, GLX, OpenCL, OpenMAX, VDPAU, VAAPI, XvMC or even NIR then? :frog: 
They are important too, aren't they?
No I won't add them :smile: 
Yes, you can go ahead and PR all the mesa packages from both official repos and AUR.

**Comment by Kerrung** [comment]
> Yes I have read your PR. But then what about OpenGL ES, EGL, GLX, OpenCL, OpenMAX, VDPAU, VAAPI, XvMC or even NIR then? 
> They are important too, aren't they?
> No I won't add them 
> Yes, you can go ahead and PR all the mesa packages from both official repos and AUR.

Thanks for the clarification, I understand you.

**Comment by Kerrung** [comment]
I deleted my fork.

**Comment by Tk-Glitch** [comment]
I mean, yes, you could do that. Is it important though? You could also argue that ACO compatibility isn't explicit in the pkgdesc either. I prefer to stay in check with all other existing mesa packages regarding something that trivial.
Don't feel bad about it btw : https://www.mesa3d.org/intro.html
"The Mesa project began as an open-source implementation of the OpenGL specification". It's historical.

**Comment by Kerrung** [comment]
I was wondering why in the description other than OpenGL you do not specify Vulkan but specify only OpenGL. And so, I received an answer to what interested me. Thank you.

**Pull request closed without merging**
