### PR TITLE
wine-tkg-git: move usvfs patch to legacy

### PR DESCRIPTION
**Pull request by telans**
I think this is all I need to do right? 

https://source.winehq.org/git/wine.git/commit/ee266aba74809b0fb4833f2d2762d3c687be4dd0

https://bugs.winehq.org/show_bug.cgi?id=47833#c4

Fails to patch currently

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
Yes that's all you need to do to make it a "legacy" patch. But what about the second hunk of the patch?
```
@@ -801,7 +801,8 @@ HANDLE WINAPI FindFirstFileExW( LPCWSTR filename, FINDEX_INFO_LEVELS level,
         }
 
         info->data_len = io.Information;
-        if (!has_wildcard || info->data_len < info->data_size - max_entry_size)
+        /* Disable this check because USVFS underflows data_len */
+        if (!has_wildcard /*|| info->data_len < info->data_size - max_entry_size*/)
         {
             if (has_wildcard)  /* release unused buffer space */
                 HeapReAlloc( GetProcessHeap(), HEAP_REALLOC_IN_PLACE_ONLY,
```
Is that still needed for USVFS to work properly?

**Comment by telans** [comment]
I wouldn't think so, as it's reported fixed without it.

**Comment by Tk-Glitch** [comment]
That what I'd assume too. We'll see.

**Comment by rsw0x** [comment]
Is part of this patch still needed?
From the [reddit thread](https://www.reddit.com/r/linux_gaming/comments/d3493y/i_got_mod_organizer_2s_usvfs_running_under_wine/)(which I assume was created by the patch author)

> The patch
> 
> https://gist.github.com/qsniyg/ec21d68f9407991a1043a71fa6ffd4cf
> 
> Edit: As of wine 4.18, the second (most important) patch has been merged into wine. You'll probably be able to use it to some extent, **although there may be some subtle issues, as the first patch hasn't been merged yet.**

**Pull request merged**
