### PR TITLE
wine/proton-tkg-git; dxvk-tools: some mtune & olevel tweaks

### PR DESCRIPTION
**Pull request by skeevy420**
Moved the O level out of the *_FLAGS options to expand it and other values to winegcc/wineg++ in proton-tkg.sh in the future to allow for more optimized builds and because I've been building with -Ofast lately...I'm a bit stupid like that...

Figured I'd add an mtune option since Clear Linux uses separate mtune/march values.

Noticed that the dxvk-tools nativeopt patches didn't include mtune so I added it there as well.

### CODE REVIEW

**Comment by skeevy420** [comment]
Lol.  I really need to fix my local git setup.  As you can tell, I just copy/pasted the example name and email it suggested (to deal with some AUR packages upon OS install) and straight up forgot.

Anyhoo, added the ability for winegcc/wineg++ to use locally set O levels and to be built with mtune/march, fixed some formatting issues, and fixed a few derps when doing this all earlier.

**Comment by skeevy420** [comment]
Added the ability to set the -g/debug level.  Figure most of us don't really need it at the default -g2 (what -g is when nothing is set) and that maybe -g0 could lead to a performance boost or compile-time boost since the compiler doesn't have to worry about debugging information and that people who actually know what they're doing might want to set it to -g3 to figure out a problem.

There are still a few things that aren't covered yet.  Looks like those might be hardcoded somewhere in Proton and/or Wine.
One of these days I'll tell it "Ofast" and that's all I'm gonna find in my build logs :smile_cat:

**Comment by skeevy420** [comment]
Proton hardcoded values are now optimizable.

Squashed it all into one commit.

The biggest change is everything will use generic values by default and the the _OPTIONAL_M* variables really aren't optional anymore.  The way I figure, if someone wants optimized/tweaked stuff they should do that themselves as well as it helps maintainers out by allowing them to use the profiles as-is.

The nativeopt patch in dxvk-tools still needs patches from within Proton/Wine to use user values.  Since it isn't enabled, that wasn't on my to-do list as well as I'm unsure on the best method go about it.

**Comment by Tk-Glitch** [comment]
Hi @skeevy420 !

I have various problems with your PR.

To begin with, `-march=native` implies `-mtune=native`. So adding it has no effect on the DXVK/D9VK front. You could somehow justify a way to customize -mtune value, but that's another story and doesn't apply in this specific case.

For the big wine-related part, my two main issues are:
- You can already change -O level or whatever compiler option you want, so why add more options for that? This is completely unjustified added complexity to me. I was actually considering *removing* options on that front since clang and zapcc are basically unable to produce a fully working wine atm, and it's been the case for a little while.
- The optimization flags "enforced" by wine are there for a reason. And it's even more critical than that as currently GCC 9.1.1 with the same opts as GCC 8.3.0 breaks wine in various ways because of new internal opts. These changes are not safe at all, and I can't take that burden on my shoulders.

The debug level part is debatable but I'd say it has its uses. We actually had a very related "hidden" option that was broken upstream recently. The result was basically 10% lower package size. Performance was unchanged. I didn't try your changes to see how it would affect binary size or performance, that would be worth a try.

For the proton part, the patch doesn't do anything. Proton-tkg doesn't use Valve building env, and as such doesn't use proton build scripts. `/build/makefile_base.mak` isn't used at any point, so patching it has no effect.
Also, sourcing `proton-tkg.cfg` as is and that late means overwriting a potential user-defined profile. You can't do that :frog:

**Comment by skeevy420** [comment]
On march/mtune, while march does imply mtune, they can be used together with different values to allow for optimized builds that work across a range of processor types.  `-march` is used for the highest level CPU supported/highest level of optimizations needed and `-mtune` is used for the lowest level.  At one point, maybe still, Clear used `-march=skylake -mtune=sandybridge`.  A build like that requires a CPU with AVX at the minimum, but the compiler will also add in AVX2 and some other extensions in the binary for CPUs that support them as well.  When people talk of "targeted binaries", `-march=something mtune=something_else` is what they mean.  Having both values available would allow Lutris and other maintainers to experiment with "Clear inspired" optimized builds.  I'd personally go with `-march=icelake-client -mtune=westmere` for Intel & `-march=nzver2 -mtune=bdver2` for AMD.  If you don't have an AES enabled processor by now, then damn...

Also, depending on one's CPU and if GCC has any issues, `-march=native` might not detect everything properly, having `-mtune=native` used can be considered a backup.  Ryzen, Threadripper, Broadwell, & Skylake, and others have all needed to use both at one time or another due to GCC not supporting the processor yet  (sometimes as other CPUs).  While most people only need them set to either their arch, native, or the default generic values, there are cases where the both need to be explicitly set and advanced users might appreciate it being readily available.

That hidden option is what inspired the debug level option.  Figured "might as well take that one step farther"...that and it being hardcoded in so many places made me think "since we can't report bugs with our builds, why the do we need debugging symbols?"...then I though that maybe someone who knows what they're doing might want to be able to ramp it up from 2 to 3.

The problem with the current -O level is it doesn't actually get used by all of the Wine or Proton building processes so I moved it out to trace down why. Simply change it to -Ofast in the default state and watch all the hardcoded -O2s used; ditto with other values set in `_GCC_FLAGS`.   It's also hardcoded as `"-O2 -g"` in proton-tkg.sh (lines 198-199).  If you consider my O level issue to be a bug, then it means that both `_GCC_FLAGS` and `_OPTIONAL_MARCH` are bugged in the current state since the `-Olevel` from within `_GCC_FLAGS` not being used in a few places is what got me to start to look into this and I happened to notice that `-march=native` wasn't being used in the exact same places I wasn't seeing my custom `-Olevel`.

I'm aware that they hardcode values for a reason, that's why I made sure to use every project default as the profile defaults.  Kind of easy when they're all either -O2, -O2 -g, or -g.  The way I figure, stray from the defaults and that's on you.  Isn't that one of the features of a project such as this?  To stray from the defaults.  I mean, we ARE given a warning on it.

On Proton:  before doing that, `-O2 -g `with no corresponding `-march=native` was very common near the end of the compile which is what got me to even look at the process where I noticed that a few of the Proton build tools do pick up values from `/build/makefile_base.mak`.  A sign that it was used was seeing `-O2 -g2 -Ofast -g0` after replacing lines 198-199 with my own hardcoded values so it was clear it was getting values from both the script and from somewhere else.  After patching  `/build/makefile_base.mak`, the doubled values quit appearing.  I assure you that `/build/makefile_base.mak` effects the build.  Patch it yourself right where I do with _anything valid_ and you'll see _anything valid_ appear in the compiler output...or screw up and it'll fail...*whistles slowly*

I did make sure that everything is set to use the default values after all the changes I made.  `-g2 `is the same thing as `-g` (-g implies -g2).  `-march=x86-64` is what gcc assumes if -march isn't used, `-mtune=generic` is what gcc assumes if -mtune isn't used (they're not exactly the same or do the same things; these are also the x86_64 defaults).  If a user changes nothing, they'll get exactly what Proton expects and exactly what Wine expects and what both used as hardcoded values; so it's not like adding these will hurt and they'll help people who like to play with compiler settings by allowing them to actually use what they tell it to use.  

Would setting the Wine and Proton hardcode patches as an option be better while leaving `_O_LEVEL`, `_DEBUG_LEVEL`, and `_OPTIONAL_MTUNE` in place?  Like having to set `_wine_compiler_override=false` & `_proton_compiler_override=false` to true.  That way one would have to both set the overrides to true and change the values to stray from what Wine expects.  I could also go ahead and patch in `_GCC_FLAGS` in the same manner.

Oh, and I did a goof which might explain some issues you may have had...`x86_64` in every one of those cfgs and profiles should be `x86-64`....just got accustomed to all the underscores in the script and that one slipped by me.

**Comment by skeevy420** [comment]
Fixed that proton sourcing issue; then fixed that with a proper solution.

Changed some _ to - so -march is correct.  The dumb things that slip by...sigh

**Comment by Tk-Glitch** [comment]
Sorry for my last changes, they will definitely interfere. I didn't mean to be a pain in the ass, and I'm sorry I feel like I am.

I agree about the -mtune flag, I said it was irrelevant in the case of DXVK/D9VK (well, even -march=native is irrelevant here actually and I should remove it) since it was added with native as value and no way to change it. Sorry if I was unclear. I also agree on GCC often being wrong.

For proton, the only three things that are getting built from the actual `Proton` tree are the `lsteamclient` lib (32 & 64-bit), the `libsteam_api` lib (32-bit only) and the "steam.exe" helper, the latter being currently fully disabled in the proton script and thus unused. So yes, indeed, you'll see flags showing up during compilation, but it is effectively useless to fiddle with these except to add more things to maintain for no reason, basically. Hopefully it'll be more explicit that way.

As I said previously regarding additional options in the cfg file, I was aiming at a simplification (now effective). Considering these flags are OCD fuel with very limited benefits regarding wine performances (unless you get LTO to work again, that is), they don't have a reason to take that much room in the config file, if any at all. I have a real problem here. Maybe an optional userpatch/profile would make more sense?
I still didn't find the time to actually test the debugging level effects but I'm planning to make the "clean" `mainline` and `staging` builds act as such, and be suitable for bug reporting (it might be of help to know about it).

Thanks for helping, and I hope we'll find a common ground.

Also, Lutris builds weren't compiled with any compiler flag besides Ubuntu 16.04 defaults, so yeah, I wouldn't hold my breath for that one. Also, I left :frog:

**Comment by skeevy420** [comment]
They actually won't interfere that much.  In fact, they'll make it easier for me in some regards.  I never bothered with any of the other compilers since, personally, I use the compiler a project prefers to use and, from there, I do my stupid stuff.

Due to the way I currently have it all patched up, I can get all the optimizations down to two sets of two lines and a generic line that's empty by default, 5 config options total. -- O & Debug levels, march & mtune, & a _C_FLAGS line (for testing things like LTO by ensuring all of the build process does what we say).  Technically, the cflags line wouldn't be necessary since one can append any cflag to the olevel or debug lines, but it would make things a lot more clear from an end-user perspective if cflags had their own place.

IMHO, fretting over the number of config lines anymore is a moot point because I'm going to move them all to a single optimizations.cfg that any profile with _compiler_optimizations=true will have access to so they won't cause any more profile or config clutter than any other patch does.  I think a single line in the primary configs with an optional secondary config will be the best middle ground here...now they'll have to change an option and edit a secondary file if they want to be dumb like me :smile_cat: 

In the mean time I'm going to just close this pull request until I get all of this worked out in a better way and I'll cherrypick around that commit so people who want optimized builds can still get them until it's ready to be brought back here.  Hopefully within the next week or two.

It's your project and I'm just some random adding my own things to it.  Ultimately, you just saying no would be all the common ground that I need, though I do prefer the current method of trying to balance ease-of-use while providing ways for power-users to do their things.

**Pull request closed without merging**
