### PR TITLE
wine-tkg-git: simplify git-log queries

### PR DESCRIPTION
**Pull request by Wuestengecko**
No need to make this more complicated than it has to be.

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
It was done that way because benchmarks showed it was the fastest. But considering it's not critical at all in such usage, I'm completely okay with simpler code.

**Comment by Wuestengecko** [comment]
That's strange. Going with `[ ... ]` syntax like this makes for 4 forks with 3 execs in total (`[`, a subshell, `git` and `grep`), contrary to two fork+execs (`git` and `grep`). Where did you find these benchmarks?

**Comment by Tk-Glitch** [comment]
Very good question. It's been a while. I'll post that in here if I happen to find these again.

**Comment by Wuestengecko** [comment]
Did some testing, and whatever these benchmarks said certainly doesn't hold true anymore.

```
#!/bin/bash
for ((i=0; i < 100; i++))
do
  [ 0 -eq $(git log | grep f17544a77c0e56d61a72220119c187e0d25278e4 > /dev/null 2> /dev/null; echo $?) ]
done
```

This takes 1min 43.58s to execute. Change the 4th line to the simpler version, and the time drops by a whopping 0.3 seconds. Just `git log &> /dev/null` takes almost a second on average!

A bit of googling later and I found [this question on StackOverflow](https://stackoverflow.com/questions/3005392/how-can-i-tell-if-one-commit-is-a-descendant-of-another-commit). So the fastest way to go would be

    git merge-base --is-ancestor $commit_sha HEAD

which takes 0.14 seconds for these 100 iterations. The time increases again however the further away from HEAD the commit to test is, but it maxes out at about 62 seconds (100 it.) for the very first commit ever made.

Interesting findings, I didn't even know `merge-base` existed.

(All tests done in `src/wine-git` after `makepkg -o`.)

**Comment by Tk-Glitch** [comment]
Great findings indeed. I also didn't know about `merge-base`! Thank you very much for your testing.

**Pull request merged**
